config/routes.rb
Rails.application.routes.draw do
  get 'players/index'

  resources :players

  root 'players#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/players.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @player = Player.all
  end

  def new
      @player = Player.new
  end

  def create
      @player = Player.new(player_params)

      if @player.save
          redirect_to root_path
      end
  end

  def show 
      @player = Player.find_by(id: params[:id])
  end

  def edit
      @player = Player.find_by(id: params[:id])
  end

  def update
      @player = Player.find_by(id: params[:id])
      @player.update(player_params)
      if @player.save
      redirect_to	player_path(@player.id)
    end
  end

  def destroy
  @post = Player.find_by(id: params[:id])
  @post.destroy
  redirect_to root_path
  end

  private
      def player_params
          params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/edit.html.erb
<%= form_for @player, url: player_path(@player.id)  do |f| %>
    <%= f.text_field :nickname %><br>
    <%= f.text_field :rank %><br>
    <%= f.text_field :charisma %><br>
    <%= f.text_field :wisdom %><br>
    <%= f.submit "Edit" %>
  <% end %>

app/views/players/index.html.erb
<%= link_to 'Add new', new_player_path%>

<%= link_to 'Create', new_post_path %>
<% if @players == [] %>

 <% else %>
 <% @players.each do |player| %>
 	<p>Player <b><%= player.nickname %></b> Rank <br />
 	<%= player.rank%><br>
    <%= player.charisma %><br>
    <%= player.wisdom %><br>

 	<%= link_to 'About',player_path(player.id) %> </p>
 	<% end %>

 <%end %>

app/views/players/new.html.erb
<%= form_for @player, url: player_path  do |f| %>
    <%= f.text_field :nickname %><br>
    <%= f.text_field :rank %><br>
    <%= f.text_field :charisma %><br>
    <%= f.text_field :wisdom %><br>
   <%= f.submit "Create" %>
 <% end %>

app/views/players/show.html.erb
<p>
	<%= @player.username %> write post: <br />
    Player: <%= @player.nickname %><br />
    Rank: <%= @player.rank %><br />
    Charisma: <%= @player.charisma %><br />
    Wisdom: <%= @player.wisdom %><br />
	
</p>

<p>
	<%= link_to 'Edit', edit_player_path(@player.id) %><br />
	<%= link_to 'Delete',player_path(@player.id), method: :delete %>
</p>